name: Build armv7

on:
  workflow_dispatch:
    inputs:
      node:
        description: 'Node major version'
        required: true
        default: '16'
jobs:
  apk:
    runs-on: rpi4
    timeout-minutes: 9999
    if: github.actor == 'robertsLando'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: "Build armv7 node${{ github.event.inputs.node }} linux"
        timeout-minutes: 9999
        id: build
        run: |
          CACHE=~/.pkg-cache/custom # custom cache folder
          rm -rf $CACHE/built-*
          mkdir -p $CACHE
          export PKG_CACHE_PATH=$CACHE
          export PKG_IGNORE_TAG=true # prevents pkg-fetch to add a tag folder
          # fix error nodejs 18: selected processor does not support `yield' in ARM mode
          export CXXFLAG="-march=native -mcpu=native"
          npx pkg-fetch -n node${{ github.event.inputs.node }}
      - name: Upload node binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ~/.pkg-cache/custom/built-*
          file_glob: true
          tag: node${{ github.event.inputs.node }}
          overwrite: true
